name: FTP Deploy

on:
  push:
    branches:
      - main  # Deploy on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Upload via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4
      with:
        ftp-server: ftp://ftp.yourdomain.com
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./build  # Directory to upload
        server-dir: /public_html/  # Destination on server
